#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 22 18:36:39 2019

@author: omar
"""
import random 
#import pandas as pd
#
#data = pd.read_excel()

entero = 100
lista = random.sample(list(range(0, entero)), entero) 
a= lista[0]

for i in lista:
    if i <= a:
        a = i
print(a)

lista.sort()
